### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'get'

### ISSUE THREAD

**Issue by bao3** [blueset/efb-fb-messenger-slave#11]
#版本信息

```
EH Forwarder Bot
Version: 2.0.0b19
Python version:
3.6.9 (default, Aug 22 2019, 01:17:11)
[GCC 4.2.1 Compatible FreeBSD Clang 6.0.1 (tags/RELEASE_601/final 335540)]
Running on profile "default".

Master channel:
    Telegram Master (blueset.telegram) 2.0.0b25 # Default instance

Slave channel:
    Facebook Messenger Slave (blueset.fbmessenger) 2.0.0b14.dev4 # Default instance

Middlewares:
    No middleware is enabled.

```

#错误日志 debug

```
2019-09-19 21:55:22,769 [Level 99]: ehforwarderbot.__main__ (__main__.init; __main__.py:85)
     Initializing slave blueset.fbmessenger...
Traceback (most recent call last):
  File "/usr/local/bin/ehforwarderbot", line 11, in <module>
    load_entry_point('ehforwarderbot==2.0.0b19', 'console_scripts', 'ehforwarderbot')()
  File "/usr/local/lib/python3.6/site-packages/ehforwarderbot/__main__.py", line 269, in main
    init(conf)
  File "/usr/local/lib/python3.6/site-packages/ehforwarderbot/__main__.py", line 91, in init
    coordinator.add_channel(cls(instance_id=instance_id))
  File "/usr/local/lib/python3.6/site-packages/efb_fb_messenger_slave-2.0.0b14.dev4-py3.6.egg/efb_fb_messenger_slave/__init__.py", line 76, in __init__
  File "/usr/local/lib/python3.6/site-packages/efb_fb_messenger_slave-2.0.0b14.dev4-py3.6.egg/efb_fb_messenger_slave/utils.py", line 21, in __init__
AttributeError: 'NoneType' object has no attribute 'get'
2019-09-19 22:09:39,119 [INFO]: ehforwarderbot.__main__ (__main__.stop_gracefully; __main__.py:59)
    Valid master channel is not found.
```

**Comment by blueset** [comment]
This should be fixed in the latest version.
