### ISSUE TITLE
 Failed to send it as image, sending as document. Reason: Wrong remote file id specified: can't unserialize it. wrong last symbol

### ISSUE THREAD

**Issue by blueset** [blueset/efb-fb-messenger-slave#2]
`[mid.$gAAit_BgpF3hxJBV4GFq8tAoXA5Ti] Failed to send it as image, sending as document. Reason: Wrong remote file id specified: can't unserialize it. wrong last symbol`

```
[mid.$gAAit_BgpF3hxJBV4GFq8tAoXA5Ti] Error occurred while processing message from slave channel.
Message: <EFBMsg, <EFBChat: Tom Lynch (839810186) @ Facebook Messenger Slave>@<EFBChat: Machine learning (2443098062395256) @ Facebook Messenger Slave> [Image]: 
[😠x2]; Attributes: None; Delivering to: <efb_telegram_master.TelegramChannel object at 0x7f0efba9b780>; Edited: True; System message: False; Substitutions: None; Target messages: None; UID: mid.$gAAit_BgpF3hxJBV4GFq8tAoXA5Ti; Reactions: {}; File: None (None @ None), None; Vendor: {}>
BadRequest()
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/efb_telegram_master/slave_message.py", line 379, in slave_message_image
    reply_markup=reply_markup)
  File "/usr/local/lib/python3.6/dist-packages/efb_telegram_master/bot_manager.py", line 230, in caption_affix
    return fn(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/efb_telegram_master/bot_manager.py", line 360, in send_photo
    return self.updater.bot.send_photo(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/telegram/bot.py", line 60, in decorator
    result = func(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/telegram/bot.py", line 85, in decorator
    result = self._request.post(url, data, timeout=kwargs.get('timeout'))
  File "/usr/local/lib/python3.6/dist-packages/telegram/utils/request.py", line 278, in post
    **urlopen_kwargs)
  File "/usr/local/lib/python3.6/dist-packages/telegram/utils/request.py", line 215, in _request_wrapper
    raise BadRequest(message)
telegram.error.BadRequest: Wrong remote file id specified: can't unserialize it. wrong last symbol

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/efb_telegram_master/slave_message.py", line 140, in send_message
    tg_msg = self.slave_message_image(msg, tg_dest, msg_template, old_msg_id, target_msg_id, reply_markup)
  File "/usr/local/lib/python3.6/dist-packages/efb_telegram_master/slave_message.py", line 385, in slave_message_image
    reply_markup=reply_markup)
  File "/usr/local/lib/python3.6/dist-packages/efb_telegram_master/bot_manager.py", line 230, in caption_affix
    return fn(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/efb_telegram_master/bot_manager.py", line 342, in send_document
    return self.updater.bot.send_document(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/telegram/bot.py", line 60, in decorator
    result = func(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/telegram/bot.py", line 85, in decorator
    result = self._request.post(url, data, timeout=kwargs.get('timeout'))
  File "/usr/local/lib/python3.6/dist-packages/telegram/utils/request.py", line 278, in post
    **urlopen_kwargs)
  File "/usr/local/lib/python3.6/dist-packages/telegram/utils/request.py", line 215, in _request_wrapper
    raise BadRequest(message)
telegram.error.BadRequest: Wrong remote file id specified: can't unserialize it. wrong last symbol


```

**Comment by blueset** [comment]
```
{'ofd_ts': 1558920294342, 'delta': {'payload': [123, 34, 100, 101, 108, 116, 97, 115, 34, 58, 91, 123, 34, 100, 101, 108, 116, 97, 77, 101, 115, 115, 97, 103, 101, 82, 101, 97, 99, 116, 105, 111, 110, 34, 58, 123, 34, 116, 104, 114, 101, 97, 100, 75, 101, 121, 34, 58, 123, 34, 116, 104, 114, 101, 97, 100, 70, 98, 73, 100, 34, 58, 50, 52, 52, 51, 48, 57, 56, 48, 54, 50, 51, 57, 53, 50, 53, 54, 125, 44, 34, 109, 101, 115, 115, 97, 103, 101, 73, 100, 34, 58, 34, 109, 105, 100, 46, 36, 103, 65, 65, 105, 116, 95, 66, 103, 112, 70, 51, 104, 120, 74, 45, 107, 45, 82, 86, 113, 57, 113, 80, 49, 81, 110, 72, 119, 57, 34, 44, 34, 97, 99, 116, 105, 111, 110, 34, 58, 48, 44, 34, 117, 115, 101, 114, 73, 100, 34, 58, 53, 51, 53, 50, 51, 48, 57, 51, 55, 44, 34, 114, 101, 97, 99, 116, 105, 111, 110, 34, 58, 34, 92, 117, 100, 56, 51, 100, 92, 117, 100, 101, 48, 54, 34, 44, 34, 115, 101, 110, 100, 101, 114, 73, 100, 34, 58, 56, 51, 57, 56, 49, 48, 49, 56, 54, 44, 34, 111, 102, 102, 108, 105, 110, 101, 84, 104, 114, 101, 97, 100, 105, 110, 103, 73, 100, 34, 58, 34, 54, 53, 51, 56, 53, 54, 56, 48, 51, 57, 57, 52, 52, 52, 53, 51, 49, 56, 49, 34, 125, 125, 93, 125], 'class': 'ClientPayload'}, 'type': 'delta', 'iseq': 96214, 'queue': 100001078163495}
```
