### ISSUE TITLE
 Error #1357004 when sending request: Please try closing and re-opening your browser window.

### ISSUE THREAD

**Issue by blueset** [blueset/efb-fb-messenger-slave#4]
```
Traceback (most recent call last):

  File "/usr/local/lib/python3.6/dist-packages/fbchat/client.py", line 2278, in _parseMessage
    thread_id=thread_id, thread_type=thread_type, ts=ts, metadata=metadata, msg=m)

  File "/usr/local/lib/python3.6/dist-packages/efb_fb_messenger_slave/efms_client.py", line 384, in onMessage
    threading.Thread(target=self.on_message, args=args, kwargs=kwargs).run()

  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)

  File "/usr/local/lib/python3.6/dist-packages/efb_fb_messenger_slave/efms_client.py", line 427, in on_message
    self.attach_media(efb_msg, attachments[0])

  File "/usr/local/lib/python3.6/dist-packages/efb_fb_messenger_slave/efms_client.py", line 252, in attach_media
    url = self.fetchImageUrl(attachment['id'])

  File "/usr/local/lib/python3.6/dist-packages/efb_fb_messenger_slave/efms_client.py", line 59, in fetchImageUrl
    j = check_request(self._get(ReqUrl.ATTACHMENT_PHOTO, query={'photo_id': str(image_id)}))

  File "/usr/local/lib/python3.6/dist-packages/fbchat/utils.py", line 232, in check_request
    check_json(j)

  File "/usr/local/lib/python3.6/dist-packages/fbchat/utils.py", line 211, in check_json
    raise FBchatFacebookError('Error #{} when sending request: {}'.format(j['error'], j['errorDescription']), fb_error_code=j['error'], fb_error_message=j['errorDescription'])

fbchat.models.FBchatFacebookError: Error #1357004 when sending request: Please try closing and re-opening your browser window.
```

**Comment by Foyej10** [comment]
![Screenshot_20240116-023436_Facebook](https://github.com/ehForwarderBot/efb-fb-messenger-slave/assets/156686871/8105bd04-c3ce-4f0b-983c-a4600e01a78b)
Now how to back my facebook id
