### ISSUE TITLE
cannot import name 'logging'

### ISSUE THREAD

**Issue by bao3** [blueset/efb-fb-messenger-slave#8]
fbchat (1.7.3) ,efb-fb-messenger-slave (2.0.0b10) 

I run `efms-auth`,but get error below.

```
Traceback (most recent call last):
  File "/usr/local/bin/efms-auth", line 6, in <module>
    from efb_fb_messenger_slave.__main__ import main
  File "/usr/local/lib/python3.6/site-packages/efb_fb_messenger_slave/__init__.py", line 12, in <module>
    from fbchat import FBchatUserError, ThreadLocation, logging
ImportError: cannot import name 'logging'
```

**Comment by blueset** [comment]
Thank you for the bug report, this has been fixed in EFMS 2.0.0b13.
