### ISSUE TITLE
AttributeError: 'str' object has no attribute 'getChild'

### ISSUE THREAD

**Issue by bao3** [blueset/efb-fb-messenger-slave#9]
Python Version: 3.6
efb-fb-slave Version: 2.0.0b14.dev3
Shell : bash
Locale : zh_CN.UTF-8

```
EFB Facebook Messenger Slave Session Updater
============================================

You are running EFMS 2.0.0b14.dev3.

This will update and overwrite your EFMS token by
log into your account again manually.

You usually need to do this when you want to log into
a new account, or when the previous session is expired.

This session is written to
/root/.ehforwarderbot/profiles/default/blueset.fbmessenger

To continue, press Enter/Return.

Email: bcdefgh@gmail.com
Password:
Traceback (most recent call last):
  File "/usr/local/bin/efms-auth", line 11, in <module>
    load_entry_point('efb-fb-messenger-slave==2.0.0b14.dev3', 'console_scripts', 'efms-auth')()
  File "/usr/local/lib/python3.6/site-packages/efb_fb_messenger_slave-2.0.0b14.dev3-py3.6.egg/efb_fb_messenger_slave/__main__.py", line 34, in main
  File "/usr/local/lib/python3.6/site-packages/efb_fb_messenger_slave-2.0.0b14.dev3-py3.6.egg/efb_fb_messenger_slave/__main__.py", line 61, in run
  File "/usr/local/lib/python3.6/site-packages/fbchat/_client.py", line 72, in __init__
    self._log = self._base_log.getChild("client")
AttributeError: 'str' object has no attribute 'getChild'
```

**Comment by bao3** [comment]
UPDATE:


原因是因为 efb master 的版本过低，升级即可解决。 Closed#
